### PR TITLE
Fixed 'he.create' to accept sub Ti.UI namespaces as Ti.UI.iPad, iOS, Android...

### PR DESCRIPTION
**Pull request by jipiboily**
Hi,
  I fixed 'he.create' to accept sub Ti.UI namespaces as Ti.UI.iPad, iOS, Android. That said, I only tested it for iPad ns.

Wish you love it!

By the way, if I ever do a "pull request" with inapropriate code performance wise, let me know!

Jean-Philippe Boily

### CODE REVIEW

**Comment by jipiboily** [comment]
Forgot to tell how to use it. 

Pretty simple sample: he.create('iPad.SplitWindow')

**Comment by jipiboily** [comment]
Going to check for those test. Are you assuming people are using Helium for iOS development? To test that, I need to test iOS, iPad or Android, there is no cross-platform sub Ti.UI namespace.

What is your point of view on that?

Thanks!

**Comment by kwhinnery** [comment]
I am assuming people are using Helium for cross-platform development, definitely.  I hadn't included the sub-namespaces, but if I did, this is basically how I thought I would do it.  When you write the test case, you would need to put conditional logic in your test to detect the current platform, and make assertions based on that.  Should be pretty trivial.  If you don't do it, I probably soon will.  But i'd like it if you could do it ;)

**Comment by jipiboily** [comment]
I'll do it, just don't know when exactly. I'll be away from my computer for like 10 days. Might do it on january 4 or around...

If there's no stress on your side, let me do it!

Happy holidays!

**Comment by jipiboily** [comment]
Closing this request and opening a new one.

**Pull request closed without merging**
